### ISSUE TITLE
Proposal to make buttons hover animation faster.

### ISSUE THREAD

**Issue by aleksanyan** [MLEVN/mlevn.github.io#20]
<img width="470" alt="screen shot 2018-07-10 at 12 28 53" src="https://user-images.githubusercontent.com/4378985/42498309-e0de5c98-843c-11e8-83b8-77b2acd63e26.png">
While hovering over multiple navigation buttons, UX could be improved by making animations ~2x faster.

**Comment by SGevorg** [comment]
transform is made .2s
