### ISSUE TITLE
fix truncation of excerpt preview on card

### ISSUE THREAD

**Issue by bittlingmayer** [MLEVN/mlevn.github.io#23]
Right now we do truncation at n chars with liquid in _includes/list.html.  Really we should not do it in liquid, instead the full excerpt should be in the HTML, but overflow beyond 2 lines should be hidden with CSS.

Actual:
<img width="385" alt="screen shot 2018-07-14 at 10 35 29" src="https://user-images.githubusercontent.com/11457984/42721783-c2630f1c-8751-11e8-9ab9-52e21b6b9293.png">

Expected:
<img width="433" alt="screen shot 2018-07-14 at 10 36 04" src="https://user-images.githubusercontent.com/11457984/42721784-c6ec2d8e-8751-11e8-8857-68a3f40e9975.png">

**Comment by SGevorg** [comment]
Added css styles to fix the truncation of the text to 2 lines, removed the truncate pipe from the list.html
