### ISSUE TITLE
'redirect' layout

### ISSUE THREAD

**Issue by bittlingmayer** [MLEVN/mlevn.github.io#24]
Would be ideal to redirect mlevn.org/language to https://www.reddit.com/r/MLEVN/search?q=flair%3Alanguage&sort=new&restrict_sr=on and so on.

**Comment by SGevorg** [comment]
we can have mlevn.org/<flair> in general, no?

**Comment by bittlingmayer** [comment]
True, better than hardcoding.

But because it's static there is no way to do it server-side.

We can make the 404.html grab `location.pathname`.

And we should make sure analytics loads fast on that page, so we get stats for those links.

**Comment by bittlingmayer** [comment]
```
<html>
  <head>
    <script>
      const flairs = window.location.pathname.split('/').filter(f => f);
      const query = flairs.map(f => encodeURIComponent('flair:' + f)).join('+');
      const url = 'https://www.reddit.com/r/MLEVN/search?restrict_sr=on&q=' + query;
      window.location.replace(url);
    </script>
  </head>
  <body>
  </body>
</html>
```
We could also split on `+`.

In which cases should we actually show a 404?

**Comment by bittlingmayer** [comment]
Done.

Try:
mlevn.org/posts/language+startups

Also supports jobs, try:  
mlevn.org/jobs/language
