### ISSUE TITLE
auto-generate front-page content

### ISSUE THREAD

**Issue by bittlingmayer** [MLEVN/mlevn.github.io#6]
We can iterate through pages and get the headers or some variable to fill out the content in the right half.

Same for the latest posts.

**Comment by bittlingmayer** [comment]
Use https://www.reddit.com/r/mlevn/about.json for "signed up".

**Comment by bittlingmayer** [comment]
> We can iterate through pages and get the headers or some variable to fill out the content in the right half.

This bit is done.  The rest is not.

**Comment by bittlingmayer** [comment]
Just need to update https://github.com/MLEVN/mlevn.github.io/blob/master/_includes/timer.html to read from https://www.reddit.com/r/mlevn/about.json.

**Comment by SGevorg** [comment]
online users + members added updated once every minute
