### ISSUE TITLE
Things to do Before Launch

### ISSUE THREAD

**Issue by SGevorg** [MLEVN/mlevn.github.io#8]
1. Fix the contrast - make text more visible
2. Fix the links color - make them look like clickable links
3. Go over the content and fix the details
4. Add community rules to the sidebar of the reddit (similar to r/machinelearning)

**Comment by bittlingmayer** [comment]
Split this into a few issues, all attached to the Launch milestone

https://github.com/MLEVN/mlevn.github.io/milestone/1
